Fix build error due to undeclared MAX_DISPLAYS variable
Error was:

  retrodep/retroglue.c:859:30: error: ‘MAX_DISPLAYS’ undeclared here (not in a function)
    859 | struct MultiDisplay Displays[MAX_DISPLAYS + 1] = {};
        |                              ^~~~~~~~~~~~