Fix build error due to undeclared regs variable
Error was:

  ./sources/src/include/mmu_common.h: In function ‘is_unaligned’:
  ./sources/src/include/mmu_common.h:119:73: error: ‘regs’ undeclared (first use in this function)
    119 |     return unlikely((addr & (size - 1)) && (addr ^ (addr + size - 1)) & regs.mmu_page_size);
        |                                                                         ^~~~