Fix build error due to missing version string
Error was:

  libretro/libretro.c: In function ‘retro_get_system_info’:
  libretro/libretro.c:576:29: error: ‘PACKAGE_STRING’ undeclared (first use in this function)
    576 |    info->library_version  = PACKAGE_STRING;
        |                             ^~~~~~~~~~~~~~