Fix build error due to undeclared UAE_BASE_VERSION variable
Error was:

  sources/src/od-fs/libamiga.c: In function ‘amiga_init’:
  sources/src/od-fs/libamiga.c:139:56: error: ‘UAE_BASE_VERSION’ undeclared (first use in this function)
    139 |     printf("UAE: Initializing core derived from %s\n", UAE_BASE_VERSION);
        |                                                        ^~~~~~~~~~~~~~~~