Fix build error due to undeclared debug variable
Error was:

  sources/src/main.c: In function ‘uae_reset’:
  sources/src/main.c:742:13: error: ‘debug_dma’ undeclared (first use in this function)
    742 |         if (debug_dma) {
        |             ^~~~~~~~~