Fix build error due to missing fcntl.h header
Error was:

  sources/src/filesys.c: In function ‘do_find’:
  sources/src/filesys.c:4989:58: error: ‘O_WRONLY’ undeclared (first use in this function)
   4989 |                 openmode = (((mode & A_FIBF_READ) == 0 ? O_WRONLY
        |                                                          ^~~~~~~~