Fix build error due to undeclared picasso_vidinfo variable
Error was:

  retrodep/retroglue.c:1528:5: error: ‘picasso_vidinfo’ undeclared (first use in this function)
   1528 |     picasso_vidinfo.rowbytes = picasso_vidinfo.width * g_amiga_video_bpp;
        |     ^~~~~~~~~~~~~~~